apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kantyna.flagsConfigMapName" . }}
  labels:
    {{- include "kantyna.labels" (dict "ctx" $ "component" "flags") | nindent 4 }}
data:
  flags.json: |
    {{- toPrettyJson .Values.flags | nindent 4 }}
