{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kantyna.dbSecretName" . }}
  labels:
    {{- include "kantyna.labels" (dict "ctx" $ "component" "postgres") | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ required "postgres.password is required" .Values.postgres.password | b64enc | quote }}
{{- end }}
