{{- $components := list
  (list "orders-api" .Values.ordersApi)
  (list "payments" .Values.payments)
  (list "worker" .Values.worker)
  (list "web" .Values.web)
  (list "loadgen" .Values.loadgen) }}
{{- range $components }}
{{- $component := index . 0 }}
{{- $svc := index . 1 }}
{{- if and $svc.enabled $svc.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kantyna.serviceAccountName" (dict "ctx" $ "component" $component) }}
  labels:
    {{- include "kantyna.labels" (dict "ctx" $ "component" $component) | nindent 4 }}
  {{- if or $svc.serviceAccount.roleArn $svc.serviceAccount.annotations }}
  annotations:
    {{- with $svc.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ . | quote }}
    {{- end }}
    {{- with $svc.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
